# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'realTimeRides' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for realTimeRides
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  target 'realTimeRidesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'realTimeRidesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
